# Role and RoleBinding for variomedia-credentials in namespace default
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-variomedia:secret-reader
rules:
- apiGroups: [""] # indicates the core API group
  resources: ["secrets"]
  resourceNames: ["variomedia-credentials"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-variomedia:secret-reader
subjects:
 - apiGroup: ""
   kind: ServiceAccount
   name: cert-manager-webhook-variomedia
   namespace: cert-manager
roleRef:
  kind: Role
  name: cert-manager-webhook-variomedia:secret-reader
  apiGroup: rbac.authorization.k8s.io
